better help
aws-samples/aws-cudos-framework-deployment pull request #357
Opened 2022-09-07 12:07 UTC by iakov-aws

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-09-14 10:10 UTC, darken99 commented
We have to fix flag parameters instead

2022-09-14 11:02 UTC, iakov-aws commented
agree but this will be next release not now. For this release we can just add doc on existing

2022-09-25 08:55 UTC, darken99 requested changes

2022-09-25 08:55 UTC, darken99 commented on cid/cli.py
> +     --share-with-account (yes|no)         Share dashboard with all users in the current account
This should be flag parameter

2022-09-25 08:55 UTC, darken99 commented on cid/cli.py
> +     --update yes                          Update all existing dependancies to the latest version (Datasets and Views). Default=no
This should be flag parameter

2022-10-11 09:27 UTC, closed without merging