Bugfix: in case if exising dataset or folder the exception was raised fixing that.
aws-samples/aws-cudos-framework-deployment pull request #403
Opened 2022-11-11 06:57 UTC by iakov-aws

…for SPICE capacity

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-11-11 11:54 UTC, darken99 requested changes

2022-11-11 11:54 UTC, darken99 commented on cid/helpers/quicksight/__init__.py
>              logger.error('Folder already exists')
Please change to logger.info()

2022-11-15 09:25 UTC, iakov-aws commented on cid/helpers/quicksight/__init__.py
>              logger.error('Folder already exists')
Must be deleted

2022-11-23 13:48 UTC, darken99 approved these changes

2022-11-23 15:33 UTC, merged