Implemented init command in cli
aws-samples/aws-cudos-framework-deployment pull request #413
Opened 2022-11-21 13:19 UTC by gaborschulz

*Description of changes:*
Implemented init command in the CLI

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-02 09:26 UTC, iakov-aws requested changes

2022-12-02 09:26 UTC, iakov-aws commented on cid/commands/cmd_init.py
> +        self.aws_partition = get_parameter("aws-partition", "Please, choose an AWS partition", choices=["aws", "aws-cn"], default="aws")
not needed. you can get it from the current region

```
import boto3

session = boto3.Session()
for partition in session.get_available_partitions():
    for region in session.get_available_regions('quicksight', partition):
        print(region, partition)
```

2022-12-02 09:26 UTC, iakov-aws commented on cid/commands/cmd_init.py
> +        if logger:
what is wrong with module level logger variable?

2022-12-02 09:26 UTC, iakov-aws commented on cid/commands/cmd_init.py
> +        except self.cid.glue.client.exceptions.AlreadyExistsException:
good

2022-12-02 09:26 UTC, iakov-aws commented on cid/commands/cmd_init.py
> +        except Exception as ex:  # pylint: disable=broad-except
Any Exception other than "Already exists " must fail the process

2022-12-02 09:26 UTC, iakov-aws commented on cid/commands/cmd_init.py
> +                    exit(1)
CidCritical, not exit

2022-12-02 09:26 UTC, iakov-aws commented on cid/commands/cmd_init.py
> +            print("\tQuickSight Edition...\tSubscribed")
And if not?

2022-12-02 09:26 UTC, iakov-aws commented on cid/helpers/account_map.py
>  import csv
I would suggest to revert all changes here as irrelevant.

2022-12-02 09:26 UTC, iakov-aws commented on cid/cli.py
> +@click.option("--qs-notification-email", help="QuickSight Notification Email", default="")
please choose if you use click options or prameters

click options are more difficult to provide with contextual defaults

2022-12-02 09:26 UTC, iakov-aws commented
great job. Please review the comments and fix conflicts

2022-12-06 11:16 UTC, gaborschulz-aws commented on cid/commands/cmd_init.py
> +            self._logger.debug("WARNING: Cannot create glue role")
Fixed

2022-12-06 12:36 UTC, gaborschulz commented on cid/utils.py
> +        raise Exception(f'CUR BucketPath={parts[0]} format is not recognized. It must be s3://(bucket)/cur or s3://{bucket}/{curprefix}/{curname}/{curname} ')  # pylint: disable=line-too-long
Does the CidError exception already exist or should I create it from scatch?

2022-12-06 12:46 UTC, iakov-aws commented on cid/utils.py
> +        raise Exception(f'CUR BucketPath={parts[0]} format is not recognized. It must be s3://(bucket)/cur or s3://{bucket}/{curprefix}/{curname}/{curname} ')  # pylint: disable=line-too-long
Yes it exists 

There are two exceptions for now
CidError for regular exception
CidCritical for terminating program in lambda or cli. 

For sure exceptions can be more specrec if needed.

2022-12-06 15:05 UTC, gaborschulz commented on cid/commands/cmd_init.py
> +    def _create_glue_crawler(self):
I'm not sure what the question is here, could you please, elaborate?

2022-12-06 15:22 UTC, iakov-aws commented on cid/commands/cmd_init.py
> +    def _create_glue_crawler(self):
Sure. This looks pretty empty. If this is WIP it is fine, but not for a final merge.

2022-12-07 14:06 UTC, closed without merging