Add recursive on version bump
aws-samples/aws-cudos-framework-deployment pull request #429
Opened 2022-12-19 08:56 UTC by tbuatois

Automatic detection of CID major version bump and ask user for recursive update. 

*Description of changes:*
- Various bug fixes 
- Addition of cid_version on template class from Description parameters 
- Additional information about cid_version in status command 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-12-19 15:43 UTC, darken99 commented on cid/helpers/quicksight/template.py
> +    def arn(self) -> str:
https://github.com/aws-samples/aws-cudos-framework-deployment/blob/9dac00ac6543579552880bcbe09351a8ed61cd4a/cid/helpers/quicksight/resource.py#L12

2022-12-25 20:18 UTC, iakov-aws commented on cid/export.py
> +                "Principal": f'arn:aws:iam::{reader_account_id}:root' if reader_account_id != '*' else '*',
Good catch

2022-12-25 20:19 UTC, iakov-aws commented on cid/export.py
> +                raise CidCritical("No analyses was found, please save your dashboard as an analyse first")
Agree

2022-12-26 18:11 UTC, iakov-aws commented on cid/helpers/quicksight/template.py
> +    def __init__(self, str_version):
suggestion: 

```
    def __init__(self, version):
        if isinstance(version, __class__):
            self.major, self.minor, self.build = version.major, version.minor, version.build 
        elif isinstance(version, str):
            self.major, self.minor, self.build = self._parse(str_version)
        else:
            raise TypeError(f'{version} must be {__class__} or string')
```

then all other functions can be simplier

```
 def compatible_versions(self, version) -> bool:
        """
            Return True when both version are on the same major branch
        """
        return CidVersion(version).major == self.major
```

2023-01-02 15:48 UTC, iakov-aws requested changes
thanks for your updates. please can you remove click.echo changes and we are ready to merge

2023-01-02 15:53 UTC, iakov-aws commented on cid/helpers/quicksight/dashboard.py
> +        print(f"  CID Version (deployed, latest): {cid_version}, {cid_version_latest}")
not clear what is CID version here. probably can be rephrased:

print(f" Deployed Version={cid_version}->Latest TemplateVersion= {cid_version_latest}")

2023-01-02 15:53 UTC, iakov-aws commented on cid/helpers/quicksight/template.py
>  class Template(CidQsResource):
Need a couple of spaces here

2023-01-03 14:49 UTC, iakov-aws approved these changes

2023-01-03 14:51 UTC, merged