terraform-modules: Adds tags input for tf managed s3 buckets
aws-samples/aws-cudos-framework-deployment pull request #885
Opened 2024-07-09 20:56 UTC by userhas404d

*Issue #, if available:*

*Description of changes:*

Adds tags to tf managed s3 buckets.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-07-10 07:38 UTC, iakov-aws commented
@sean-nixon can you check this as well?

2024-07-11 19:08 UTC, sean-nixon requested changes
@userhas404d Can you please also update the module documentation with [terraform-docs](https://terraform-docs.io/)? There is a configuration file already in each module, so all you need to do is point it at each directory (e.g. `terraform-docs terraform-modules/cur-setup-destination`)

2024-07-11 22:33 UTC, sean-nixon approved these changes
LGTM @iakov-aws

2024-07-12 15:11 UTC, userhas404d commented on terraform-modules/cur-setup-destination/README.md
> +### tags
looks like it was just moved: https://github.com/aws-samples/aws-cudos-framework-deployment/pull/885/files#diff-04390840bcd9334e45df1375f94e9e356d3d091fcccdc5bf88b77c4ddcf0c4d2R113

2024-07-12 15:56 UTC, iakov-aws approved these changes

2024-07-12 15:56 UTC, merged

2024-07-12 15:57 UTC, iakov-aws commented
Great contribution! TY